source: J0605+3757
par-directory: results/
tim-directory: /nanograv/timing/releases/15y/toagen/releases/2021.02.21-b756d85/
timing-model: J0605+3757_PINT_20210304.wb.par
compare-model: archive/J0605+3757.14yrbw.par
toas:
- J0605+3757.Rcvr1_2.GUPPI.15y.x.wb.tim
- J0605+3757.Rcvr_800.GUPPI.15y.x.wb.tim

free-params: [ELONG, ELAT, PMELONG, PMELAT, PX, F0, F1, A1, PB, T0, E, OM, JUMP1,
  DMJUMP1, DMJUMP2]  # parameters not included here will be frozen
free-dmx: Yes
toa-type: WB
fitter: WidebandTOAFitter
n-iterations: 1
ephem: DE440
bipm: BIPM2019

noise: # control noise runs, apply results
  results-dir: /nanograv/share/15yr/timing/intermediate/noise-chains/
dmx:  # control dmx windowing/fixing
  ignore-dmx: false
  fratio: 1.1
  max-sw-delay: 0.1 # finer binning when solar wind delay > threshold (us)
  custom-dmx: [] # designated by [mjd_low,mjd_hi,binsize]
ignore: # toa excision
  mjd-start:
  mjd-end:
  snr-cut: 25
  bad-toa:
  bad-range:
  bad-epoch:

changelog:
- '2020-12-09 scott.ransom INIT: YAML autogenerated by write_initial_configs.py'
