source: J0605+3757
par-directory: results/
tim-directory: /nanograv/timing/releases/15y/toagen/releases/2021.08.25-9d8d617/
timing-model: J0605+3757_PINT_20210924.wb.par
compare-model: archive/J0605+3757_PINT_20210908.wb.par
toas:
- J0605+3757.Rcvr1_2.GUPPI.15y.x.wb.tim
- J0605+3757.Rcvr_800.GUPPI.15y.x.wb.tim

free-params: [ELONG, ELAT, PMELONG, PMELAT, PX, F0, F1, A1, PB, T0, E, OM, JUMP1,
  DMJUMP1, DMJUMP2]
free-dmx: Yes
toa-type: WB
fitter: WidebandDownhillFitter
n-iterations: 20
ephem: DE440
bipm: BIPM2019

dmx:  # control dmx windowing/fixing
  ignore-dmx: false
  fratio: 1.1
  max-sw-delay: 0.1 # finer binning when solar wind delay > threshold (us)
  custom-dmx: [] # designated by [mjd_low,mjd_hi,binsize]

intermediate-results: # use results from previous runs
  noise-dir: /nanograv/share/15yr/timing/intermediate/20210908.Noise.wb.351af4e/
  compare-noise-dir: /nanograv/share/15yr/timing/intermediate/20210831.Noise.wb.5933923/
  excised-tim: /nanograv/share/15yr/timing/intermediate/20210828.Outlier.wb.5719caa/J0605+3757.wb/J0605+3757.wb_excise.tim
  no-corner: true
ignore: # toa excision
  mjd-start:
  mjd-end: 59072.0
  snr-cut: 25
  bad-range:
  bad-file:

changelog:
- '2020-12-09 scott.ransom INIT: YAML autogenerated by write_initial_configs.py'
- '2021-03-05 anne.archibald READY_FOR: v0.9'
- '2021-08-03 joe.swiggum CURATE: no manual cuts to inspect'
- '2021-09-22 ingrid.stairs READY_FOR: v1.0'
- '2021-09-24 joe.swiggum NOTE: updated AO/GBO coords (pint v0.8.3) and refit'
