# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "Notebook Pipeline (Ubuntu)"

on:
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Install pdflatex
      run: |
        sudo apt-get update
        sudo apt-get install texlive-latex-base pdftk latex2html
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: pulsar
    - name: Install Dependencies & Main Code
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        mamba install -c conda-forge cython=0.29.36 tempo2 scikit-sparse
        python -m pip install -e .
    - name: Test with Standard Pulsar
      run: |
        export PULSAR_NAME='J0605+3757'
        export JUPYTER_PLATFORM_DIRS=1 && jupyter --paths
        tree tests
        pytest tests/test_run_notebook.py -n auto -k $PULSAR_NAME
        mv tmp-* nb_outputs
    - name: Archive Notebook Output Files
      uses: actions/upload-artifact@v3
      with:
        name: TestNB-OutputFiles
        path: |
          nb_outputs
        
